packages:
  - 'config/*'
  - 'apps/*'
  - 'packages/*'

catalogs:
  vanilla-extract-core:
    '@vanilla-extract/css': '^1.17.4'
    '@vanilla-extract/recipes': '^0.5.7'

  vanilla-extract-utils:
    '@vanilla-extract/sprinkles': '^1.6.5'
    '@vanilla-extract/vite-plugin': '^5.1.0'

  vite-core:
    'vite': '^7.0.0'

  vite-plugins:
    '@vitejs/plugin-react': '^4.5.2'
