/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/posts/{post-id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게시물 상세 조회
     * @description 커뮤니티에서 글을 상세 조회합니다.
     */
    get: operations['getPostDetail'];
    /**
     * 게시물 수정
     * @description 커뮤니티에서 글을 수정합니다.
     */
    put: operations['updatePost'];
    post?: never;
    /**
     * 게시물 삭제
     * @description 커뮤니티에서 글을 삭제합니다.(소프트 딜리트)
     */
    delete: operations['deletePost'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게시물 전체 조회
     * @description 커뮤니티에서 모든 글을 조회합니다.
     */
    get: operations['getAllPosts'];
    put?: never;
    /**
     * 게시물 작성
     * @description 커뮤니티에 글을 작성합니다.
     */
    post: operations['createPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{post-id}/likes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 게시글 좋아요 생성
     * @description 유저가 커뮤니티 게시글에 좋아요를 생성합니다.
     */
    post: operations['createPostLike'];
    /**
     * 게시글 좋아요 삭제
     * @description 유저가 커뮤니티 게시글에 생성했던 좋아요를 삭제합니다.
     */
    delete: operations['deletePostLike'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{post-id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 댓글 목록 조회
     * @description 커뮤니티 게시글의 댓글 목록을 조회합니다.
     */
    get: operations['getComments'];
    put?: never;
    /**
     * 댓글 작성
     * @description 커뮤니티 게시글에 댓글을 작성합니다.
     */
    post: operations['createComment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{post-id}/comments/{comment-id}/reply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 대댓글 조회
     * @description 커뮤니티 댓글의 대댓글을 조회합니다.
     */
    get: operations['getCommentReply'];
    put?: never;
    /**
     * 대댓글 작성
     * @description 유저가 커뮤니티 댓글에 대댓글을 작성합니다.
     */
    post: operations['createCommentReply'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oauth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 토큰 재발급 */
    post: operations['reissue'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oauth/kakao/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 로그아웃 */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oauth/kakao/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 카카오 로그인
     * @description 카카오 API를 통해 로그인합니다.
     */
    get: operations['kakaoCallback_1'];
    put?: never;
    /**
     * 카카오 로그인 - POST
     * @description 카카오 API를 통해 로그인합니다. POST 요청을 사용하여 Body에 필요한 데이터를 받아옵니다.
     */
    post: operations['kakaoCallback'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/insurances/reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 보험 상품 추천
     * @description 보험 상품을 추천 받습니다.
     */
    post: operations['issueReport'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이미지 업로드 API
     * @description mediaType을 통해 PresignedUrl을 발급받습니다.
     */
    post: operations['createdUrls'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 유저 프로필 수정
     * @description 유저의 프로필을 수정합니다.
     */
    patch: operations['updateProfile'];
    trace?: never;
  };
  '/posts/{post-id}/comments/{comment-id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 댓글 삭제
     * @description 커뮤니티 게시글의 댓글을 삭제합니다.
     */
    delete: operations['deleteComment'];
    options?: never;
    head?: never;
    /**
     * 댓글 수정
     * @description 커뮤니티 게시글의 댓글을 수정합니다.
     */
    patch: operations['updateComment'];
    trace?: never;
  };
  '/posts/{post-id}/comments/{comment-id}/reply/{comment-reply-id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 대댓글 삭제
     * @description 유저가 커뮤니티 댓글의 대댓글을 삭제합니다.
     */
    delete: operations['deleteCommentReply'];
    options?: never;
    head?: never;
    /**
     * 대댓글 수정
     * @description 유저가 커뮤니티 댓글의 대댓글을 수정합니다.
     */
    patch: operations['updateCommentReply'];
    trace?: never;
  };
  '/users/me/report-summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 최근 추천 리포트 요약 조회
     * @description 가장 최근에 추천 받은 보험 리포트의 요약 내용을 조회합니다.
     */
    get: operations['getMyLastInsuranceReportSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내가 쓴 글 조회
     * @description 내가 쓴 글을 조회합니다.
     */
    get: operations['getMyPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내가 쓴 댓글 조회
     * @description 내가 쓴 댓글을 조회합니다.
     */
    get: operations['getMyComments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 유저 정보 조회
     * @description 유저의 정보를 조회합니다.
     */
    get: operations['getInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user-infos/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 직업 목록 조회
     * @description 선택 가능한 직업 목록을 조회합니다.
     */
    get: operations['getJobs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user-infos/insurances/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보험 추천 시 선택 사항 항목 조회
     * @description 보험 추천 시 보험 상품의 선택 사항 항목을 조회합니다.
     */
    get: operations['getInsurancesOptions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user-infos/diagnosed-disease': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 진단 받은 질병 목록 조회
     * @description 선택 가능한 진단 받았던 질병 목록을 조회합니다.
     */
    get: operations['getDiagnosedDisease'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user-infos/coverage-select': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보장 상황 목록 조회
     * @description 선택 가능한 보장 상황 목록을 조회합니다.
     */
    get: operations['getCoverageSelect'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/trend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 인기 게시물 목록 조회
     * @description 커뮤니티에서 인기글 목록을 조회합니다.
     */
    get: operations['getTrendPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게시물 검색
     * @description 검색 키워드를 기반으로 게시물을 검색합니다.
     */
    get: operations['searchPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/insurances/reports/{insurance-report-id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보험 추천 리포트 조회
     * @description 보험 추천 리포트를 조회합니다.
     */
    get: operations['getReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/insurances/reports/{insurance-report-id}/surgery': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보험 추천 리포트 수술 섹션 조회
     * @description 보험 추천 리포트 수술 섹션을 조회합니다.
     */
    get: operations['getReportSurgerySection'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/insurances/reports/{insurance-report-id}/major-disease': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보험 추천 리포트 큰병 섹션 조회
     * @description 보험 추천 리포트 큰병 섹션 조회합니다.
     */
    get: operations['getReportMajorSection'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/insurances/reports/{insurance-report-id}/hospitalization': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보험 추천 리포트 일당입원비 상세 조회
     * @description 보험 추천 리포트 일당입원비를 상세 조회합니다.
     */
    get: operations['getHospitalizationSection'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/insurances/reports/{insurance-report-id}/disability': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보험 추천 리포트 장해 섹션 조회
     * @description 보험 추천 리포트 장해 섹션을 조회합니다.
     */
    get: operations['getDisabilitySection'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/insurances/reports/{insurance-report-id}/death': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 보험 추천 리포트 사망 섹션 조회
     * @description 보험 추천 리포트 사망 섹션을 조회합니다.
     */
    get: operations['getDeathSection'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oauth/kakao/unlink': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 회원 탈퇴 */
    delete: operations['unlink'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PostUpdateRequest: {
      /**
       * @description 제목
       * @example ㅇㅇ
       */
      newTitle: string;
      /**
       * @description 내용
       * @example ㅇㅇㅇ
       */
      newContent: string;
      /**
       * @description 카테고리
       * @example INFORMATION
       */
      newCategory: string;
      /** @description 수정된 이미지 목록 */
      updatedImages: components['schemas']['UpdateImageRequest'][];
      /** @description 삭제할 이미지 ID 목록 */
      deleteImageIds: number[];
    };
    /** @description 수정된 이미지 목록 */
    UpdateImageRequest: {
      /**
       * Format: int64
       * @description 이미지 ID
       */
      id?: number;
      /** @description 새 이미지 URL (변경 없으면 null) */
      imageUrl?: string;
      /**
       * Format: int32
       * @description 순서, 1부터 시작
       */
      sequence?: number;
    };
    BaseResponsePostCreateResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['PostCreateResponse'];
    };
    PostCreateResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       */
      postId?: number;
    };
    PostCreateRequest: {
      /**
       * @description 글 제목
       * @example 아니
       */
      title: string;
      /**
       * @description 내용
       * @example 저희 대상타면 어떡하나요 ㅈㅉ로?
       */
      content: string;
      /**
       * @description 카테고리
       * @example QNA
       */
      category: string;
      /** @description 이미지 url */
      imageUrls?: string[];
    };
    BaseResponseVoid: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: Record<string, never>;
    };
    CommentCreateRequest: {
      /**
       * @description 댓글 내용
       * @example 좋은 글이네요
       */
      content: string;
      /** @description 이미지 url 목록. url 이 존재하지 않는 경우에도 빈 리스트를 요구 */
      imageUrls: string[];
    };
    CommentReplyCreateRequest: {
      /**
       * @description 본문
       * @example 대댓글 작성하기 ~
       */
      content: string;
      /** @description 이미지 url 목록. url 이 존재하지 않는 경우에도 빈 리스트를 요구 */
      imageUrls: string[];
    };
    BaseResponseTokenReissueResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['TokenReissueResponse'];
    };
    TokenReissueResponse: {
      /** @description 액세스 토큰 */
      accessToken?: string;
      /** @description 리프레쉬 토큰 */
      refreshToken?: string;
    };
    BaseResponseString: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: string;
    };
    OAuthLoginRequest: {
      code: string;
      redirectUrl?: string;
    };
    BaseResponseKaKaoLoginResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['KaKaoLoginResponse'];
    };
    KaKaoLoginResponse: {
      /**
       * Format: int64
       * @description 유저 PK
       * @example 1
       */
      userId?: number;
      /** @description 액세스 토큰 */
      accessToken?: string;
      /** @description 리프레쉬 토큰 */
      refreshToken?: string;
    };
    InsuranceReportRequest: {
      /**
       * @description 실명
       * @example 김재헌
       */
      name: string;
      /**
       * Format: date
       * @description 생년월일
       * @example 2001-09-04
       */
      birthDate: string;
      /**
       * @description 성별
       * @example MALE
       * @enum {string}
       */
      gender: 'MALE' | 'FEMALE';
      /**
       * @description 직업
       * @example STUDENT
       * @enum {string}
       */
      job:
        | 'OFFICE_WORK'
        | 'SERVICE_SALES'
        | 'PROFESSIONAL'
        | 'SELF_EMPLOYED'
        | 'PRODUCTION_SITE'
        | 'DRIVER_DELIVERY'
        | 'HOMEMAKER'
        | 'STUDENT'
        | 'UNEMPLOYED'
        | 'FREELANCER'
        | 'ETC';
      /**
       * @description 결혼 여부
       * @example false
       */
      isMarried: boolean;
      /**
       * @description 자녀 여부
       * @example false
       */
      hasChild: boolean;
      /**
       * @description 운전자 여부
       * @example false
       */
      isDriver: boolean;
      /**
       * @description 최근 5년 이내에 진단 또는 치료받은 질병 목록
       * @example [
       *       "CANCER",
       *       "HEART"
       *     ]
       */
      diseaseHistory: (
        | 'CANCER'
        | 'CEREBROVASCULAR'
        | 'HEART'
        | 'RESPIRATORY'
        | 'RIVER'
        | 'KIDNEY'
        | 'MENTAL'
        | 'CHRONIC'
        | 'NONE'
      )[];
      /**
       * @description 가족 구성원이 진단 또는 치료받은 질병 목록
       * @example [
       *       "CANCER",
       *       "RIVER"
       *     ]
       */
      familyHistory: (
        | 'CANCER'
        | 'CEREBROVASCULAR'
        | 'HEART'
        | 'RESPIRATORY'
        | 'RIVER'
        | 'KIDNEY'
        | 'MENTAL'
        | 'CHRONIC'
        | 'NONE'
      )[];
      /**
       * @description 보장 순위 카테고리 입력
       * @example {
       *       "MAJOR_DISEASE": 1,
       *       "ESSENTIAL_ONLY": 2
       *     }
       */
      coveragePreferences: {
        [key: string]: number;
      };
      /**
       * Format: int32
       * @description 희망 최소 가격
       * @example 70000
       */
      minPremium: number;
      /**
       * Format: int32
       * @description 희망 최대 가격
       * @example 150000
       */
      maxPremium: number;
      /**
       * @description 납입구조
       * @enum {string}
       */
      renewableType?: 'RENEWABLE' | 'NON_RENEWABLE';
      /**
       * @description 환급구조
       * @enum {string}
       */
      refundType?: 'PROTECTION_ONLY' | 'PARTIAL_RETURN' | 'FULL_RETURN';
      /**
       * @description 납부기간
       * @enum {string}
       */
      paymentPeriod?: 'YEAR_10' | 'YEAR_20' | 'YEAR_30';
      /**
       * @description 만기
       * @enum {string}
       */
      maturityAge?: 'OLD_80' | 'OLD_100';
    };
    BaseResponseIssueInsuranceReportResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['IssueInsuranceReportResponse'];
    };
    IssueInsuranceReportResponse: {
      /** Format: uuid */
      insuranceReportId?: string;
    };
    PresignedUrlRequest: {
      /** @description 파일 형식 */
      mediaType?: string[];
    };
    BaseResponsePresignedUrlResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['PresignedUrlResponse'];
    };
    PresignedUrlResponse: {
      presignedUrls?: string[];
    };
    UserUpdateProfileRequest: {
      /**
       * @description 닉네임
       * @example 김재헌
       */
      nickname?: string;
      /** @description 프로필 이미지 url */
      profileImageUrl?: string;
    };
    CommentUpdateRequest: {
      /**
       * @description 수정할 댓글 내용
       * @example 좋은 글이네요
       */
      content?: string;
      /** @description 수정된 이미지 목록 */
      updatedImages: components['schemas']['UpdateImageRequest'][];
      /** @description 삭제할 이미지 ID 목록 */
      deleteImageIds: number[];
    };
    CommentReplyUpdateRequest: {
      /**
       * @description 수정할 대댓글 내용
       * @example 좋은 댓글이네요
       */
      content?: string;
      /** @description 수정된 이미지 목록 */
      updatedImages: components['schemas']['UpdateImageRequest'][];
      /** @description 삭제할 이미지 ID 목록 */
      deleteImageIds: number[];
    };
    BaseResponseInsuranceReportSummaryResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['InsuranceReportSummaryResponse'];
    };
    InsuranceReportSummaryResponse: {
      /** Format: uuid */
      insuranceReportId?: string;
      productName?: string;
      company?: string;
      keywordChips?: string[];
      statuses?: components['schemas']['ShowCoverageStatus'][];
    };
    ShowCoverageStatus: {
      target?: string;
      status?: string;
    };
    BaseResponseSliceResponseMyPostSummaryResponseLong: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['SliceResponseMyPostSummaryResponseLong'];
    };
    /** @description 데이터 목록 */
    MyPostSummaryResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       */
      postId?: number;
      /**
       * @description 제목
       * @example string
       */
      title?: string;
      /**
       * @description 내용
       * @example 저만 삼성보험 건강보험 괜찮나요?
       */
      content?: string;
      /**
       * Format: int32
       * @description 댓글 수
       * @example 8
       */
      commentCount?: number;
      /**
       * Format: date-time
       * @description 작성 시간
       */
      createdAt?: string;
      /**
       * Format: int32
       * @description 좋아요 수
       */
      likeCount?: number;
      /** @description 사용자 좋아요 여부 */
      isLike?: boolean;
    };
    SliceResponseMyPostSummaryResponseLong: {
      /** @description 데이터 목록 */
      content?: components['schemas']['MyPostSummaryResponse'][];
      /**
       * Format: int64
       * @description 다음 커서
       */
      nextCursor?: number;
      /** @description 마지막 페이지 여부 */
      isLast?: boolean;
    };
    BaseResponseSliceResponseMyCommentSummaryResponseLong: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['SliceResponseMyCommentSummaryResponseLong'];
    };
    /** @description 데이터 목록 */
    MyCommentSummaryResponse: {
      /**
       * Format: int64
       * @description 댓글 ID
       */
      commentId?: number;
      /**
       * Format: int64
       * @description 댓글을 작성한 게시글 ID
       */
      postId?: number;
      /**
       * @description 댓글 내용
       * @example 저도요
       */
      content?: string;
      /**
       * Format: date-time
       * @description 작성 시간
       */
      createdAt?: string;
    };
    SliceResponseMyCommentSummaryResponseLong: {
      /** @description 데이터 목록 */
      content?: components['schemas']['MyCommentSummaryResponse'][];
      /**
       * Format: int64
       * @description 다음 커서
       */
      nextCursor?: number;
      /** @description 마지막 페이지 여부 */
      isLast?: boolean;
    };
    BaseResponseUserProfileResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['UserProfileResponse'];
    };
    UserProfileResponse: {
      /**
       * Format: int64
       * @description 유저 PK
       * @example 1
       */
      userId?: number;
      /**
       * @description 이름
       * @example 이정연
       */
      username?: string;
      /**
       * @description 유저 닉네임
       * @example 장정훈
       */
      nickname?: string;
      /** @description 유저 프로필 사진 url */
      profileImageUrl?: string;
      /** @description 보험 추천 받았는지 여부 */
      isRecommendInsurance?: boolean;
    };
    BaseResponseJobResponses: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['JobResponses'];
    };
    JobResponse: {
      /** @enum {string} */
      job?:
        | 'OFFICE_WORK'
        | 'SERVICE_SALES'
        | 'PROFESSIONAL'
        | 'SELF_EMPLOYED'
        | 'PRODUCTION_SITE'
        | 'DRIVER_DELIVERY'
        | 'HOMEMAKER'
        | 'STUDENT'
        | 'UNEMPLOYED'
        | 'FREELANCER'
        | 'ETC';
      displayName?: string;
    };
    JobResponses: {
      jobs?: components['schemas']['JobResponse'][];
    };
    BaseResponseInsuranceOptionsResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['InsuranceOptionsResponse'];
    };
    InsuranceOptionsResponse: {
      renewableTypes?: components['schemas']['RenewableTypeResponse'][];
      refundTypes?: components['schemas']['RefundTypeResponse'][];
      paymentPeriods?: components['schemas']['PaymentPeriodResponse'][];
      maturityAges?: components['schemas']['MaturityAgeResponse'][];
    };
    MaturityAgeResponse: {
      /** @enum {string} */
      maturityAge?: 'OLD_80' | 'OLD_100';
      displayName?: string;
    };
    PaymentPeriodResponse: {
      /** @enum {string} */
      paymentPeriod?: 'YEAR_10' | 'YEAR_20' | 'YEAR_30';
      displayName?: string;
    };
    RefundTypeResponse: {
      /** @enum {string} */
      refundType?: 'PROTECTION_ONLY' | 'PARTIAL_RETURN' | 'FULL_RETURN';
      displayName?: string;
    };
    RenewableTypeResponse: {
      /** @enum {string} */
      renewableType?: 'RENEWABLE' | 'NON_RENEWABLE';
      displayName?: string;
    };
    BaseResponseDiagnosedDiseaseResponses: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['DiagnosedDiseaseResponses'];
    };
    DiagnosedDiseaseResponse: {
      /** @enum {string} */
      diagnosedDisease?:
        | 'CANCER'
        | 'CEREBROVASCULAR'
        | 'HEART'
        | 'RESPIRATORY'
        | 'RIVER'
        | 'KIDNEY'
        | 'MENTAL'
        | 'CHRONIC'
        | 'NONE';
      displayName?: string;
      description?: string;
    };
    DiagnosedDiseaseResponses: {
      diagnosedDiseases?: components['schemas']['DiagnosedDiseaseResponse'][];
    };
    BaseResponseCoveragePreferenceResponses: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['CoveragePreferenceResponses'];
    };
    CoveragePreferenceResponse: {
      /** @enum {string} */
      coveragePreference?:
        | 'MAJOR_DISEASE'
        | 'DEATH_BENEFIT'
        | 'ESSENTIAL_ONLY'
        | 'ACCIDENT_PREDICTION'
        | 'SURGERY_COVERAGE'
        | 'MAXIMUM_COVERAGE'
        | 'RECOMMENDED_OPTION';
      description?: string;
    };
    CoveragePreferenceResponses: {
      coveragePreferenceResponses?: components['schemas']['CoveragePreferenceResponse'][];
    };
    BaseResponseSliceResponsePostSummaryResponseLong: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['SliceResponsePostSummaryResponseLong'];
    };
    /** @description 데이터 목록 */
    PostSummaryResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       */
      postId?: number;
      /**
       * Format: int64
       * @description 작성자 ID
       */
      writerId?: number;
      /**
       * @description 게시글 제목
       * @example 아니
       */
      title?: string;
      /**
       * @description 게시글 내용
       * @example 장정훈 그는 누구인가
       */
      content?: string;
      /**
       * @description 작성자 닉네임
       * @example 정훈 장
       */
      writerNickname?: string;
      /** @description 작성자 프로필 사진 */
      profileImageUrl?: string;
      /**
       * Format: int32
       * @description 댓글 수
       * @example 8
       */
      commentCount?: number;
      /**
       * Format: date-time
       * @description 게시물 작성 시각
       */
      createdAt?: string;
      /**
       * Format: int32
       * @description 좋아요 수
       */
      likeCount?: number;
      /** @description 사용자의 좋아요 여부 */
      likedByCurrentUser?: boolean;
    };
    SliceResponsePostSummaryResponseLong: {
      /** @description 데이터 목록 */
      content?: components['schemas']['PostSummaryResponse'][];
      /**
       * Format: int64
       * @description 다음 커서
       */
      nextCursor?: number;
      /** @description 마지막 페이지 여부 */
      isLast?: boolean;
    };
    BaseResponsePostDetailResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['PostDetailResponse'];
    };
    /** @description 게시물 카테고리 */
    PostCategoryResponse: {
      /** @enum {string} */
      category?: 'QNA' | 'INFORMATION' | 'CONVERSATION';
      description?: string;
    };
    /** @description 이미지 url */
    PostDetailImageResponse: {
      /**
       * Format: int64
       * @description 이미지 ID
       */
      imageId?: number;
      /** @description 이미지 url */
      imageUrl?: string;
    };
    PostDetailResponse: {
      /**
       * Format: int64
       * @description 작성자 ID
       */
      writerId?: number;
      /**
       * @description 닉네임
       * @example 정훈 장
       */
      writerNickname?: string;
      /** @description 프로필 사진 url */
      profileImage?: string;
      /** @description 게시물 제목 */
      title?: string;
      /** @description 게시물 내용 */
      content?: string;
      /**
       * Format: int32
       * @description 댓글 수
       * @example 8
       */
      commentCount?: number;
      /**
       * Format: date-time
       * @description 생성 시간
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description 수정 시간
       */
      updatedAt?: string;
      /**
       * Format: int32
       * @description 좋아요 수
       */
      likeCount?: number;
      /** @description 사용자 좋아요 여부 */
      likedByCurrentUser?: boolean;
      category?: components['schemas']['PostCategoryResponse'];
      /** @description 이미지 url */
      imageUrl?: components['schemas']['PostDetailImageResponse'][];
    };
    BaseResponseSliceResponseCommentWithImagesResponseLong: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['SliceResponseCommentWithImagesResponseLong'];
    };
    /** @description 댓글 이미지 목록 */
    CommentImageResponse: {
      /** Format: int64 */
      imageId?: number;
      imageUrl?: string;
      /** Format: int32 */
      sequence?: number;
    };
    /** @description 데이터 목록 */
    CommentWithImagesResponse: {
      /**
       * Format: int64
       * @description 댓글 ID
       */
      commentId?: number;
      /**
       * Format: int64
       * @description 작성자 ID
       */
      writerId?: number;
      /** @description 작성자 닉네임 */
      writerNickname?: string;
      /** @description 작성자 프로필 이미지 */
      profileImage?: string;
      /** @description 댓글 내용 */
      content?: string;
      /**
       * Format: int32
       * @description 대댓글 개수
       */
      replyCount?: number;
      /**
       * Format: date-time
       * @description 생성 시간
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description 수정 시간
       */
      updatedAt?: string;
      /** @description 댓글 이미지 목록 */
      images?: components['schemas']['CommentImageResponse'][];
    };
    SliceResponseCommentWithImagesResponseLong: {
      /** @description 데이터 목록 */
      content?: components['schemas']['CommentWithImagesResponse'][];
      /**
       * Format: int64
       * @description 다음 커서
       */
      nextCursor?: number;
      /** @description 마지막 페이지 여부 */
      isLast?: boolean;
    };
    BaseResponseSliceResponseCommentReplyWithImagesResponseLong: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['SliceResponseCommentReplyWithImagesResponseLong'];
    };
    /** @description 대댓글 이미지 목록 */
    CommentReplyImageResponse: {
      /** Format: int64 */
      commentReplyImageId?: number;
      imageUrl?: string;
      /** Format: int32 */
      sequence?: number;
    };
    /** @description 데이터 목록 */
    CommentReplyWithImagesResponse: {
      /**
       * Format: int64
       * @description 대댓글 ID
       */
      commentReplyId?: number;
      /**
       * Format: int64
       * @description 작성자 ID
       */
      writerId?: number;
      /** @description 작성자 닉네임 */
      writerNickname?: string;
      /** @description 작성자 프로필 이미지 */
      profileImage?: string;
      /** @description 댓글 내용 */
      content?: string;
      /**
       * Format: date-time
       * @description 생성 시간
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description 수정 시간
       */
      updatedAt?: string;
      /** @description 대댓글 이미지 목록 */
      images?: components['schemas']['CommentReplyImageResponse'][];
    };
    SliceResponseCommentReplyWithImagesResponseLong: {
      /** @description 데이터 목록 */
      content?: components['schemas']['CommentReplyWithImagesResponse'][];
      /**
       * Format: int64
       * @description 다음 커서
       */
      nextCursor?: number;
      /** @description 마지막 페이지 여부 */
      isLast?: boolean;
    };
    BaseResponseTrendingPostsResponses: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['TrendingPostsResponses'];
    };
    TrendingPostsResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       */
      postId?: number;
      /**
       * Format: int64
       * @description 작성자 ID
       */
      writerId?: number;
      /**
       * @description 닉네임
       * @example 정훈 장
       */
      writerNickname?: string;
      /** @description 게시물 제목 */
      title?: string;
      /** @description 게시물 내용 */
      content?: string;
      /**
       * Format: int32
       * @description 댓글 수
       * @example 8
       */
      commentCount?: number;
      /**
       * Format: date-time
       * @description 생성 시간
       */
      createdAt?: string;
      /**
       * Format: int32
       * @description 좋아요 수
       */
      likeCount?: number;
      /** @description 사용자 좋아요 여부 */
      likedByCurrentUser?: boolean;
      category?: components['schemas']['PostCategoryResponse'];
    };
    TrendingPostsResponses: {
      posts?: components['schemas']['TrendingPostsResponse'][];
    };
    BaseResponseInsuranceReportResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['InsuranceReportResponse'];
    };
    BasicInformation: {
      name?: string;
      company?: string;
      productType?: string;
      /** Format: int32 */
      minEnrollmentAge?: number;
      /** Format: int32 */
      maxEnrollmentAge?: number;
      /** Format: int32 */
      premium?: number;
      /** @enum {string} */
      maturityAge?: 'OLD_80' | 'OLD_100';
      /** @enum {string} */
      paymentPeriod?: 'YEAR_10' | 'YEAR_20' | 'YEAR_30';
      /** @enum {string} */
      renewableType?: 'RENEWABLE' | 'NON_RENEWABLE';
      /** @enum {string} */
      refundType?: 'PROTECTION_ONLY' | 'PARTIAL_RETURN' | 'FULL_RETURN';
    };
    InsuranceReportResponse: {
      /** Format: uuid */
      reportId?: string;
      reportInformation?: components['schemas']['BasicInformation'];
      reportRationale?: components['schemas']['ReportRationale'];
      majorDisease?: components['schemas']['SectionData'];
      surgery?: components['schemas']['SectionData'];
      hospitalization?: components['schemas']['SectionData'];
      disability?: components['schemas']['SectionData'];
      death?: components['schemas']['SectionData'];
      externalUri?: string;
    };
    ReportRationale: {
      reasons?: string[];
      keywordChips?: string[];
    };
    SectionData: {
      additionalInfo?: string;
      resource?: string;
      statuses?: components['schemas']['ShowCoverageStatusDetail'][];
    };
    ShowCoverageStatusDetail: {
      target?: string;
      status?: string;
      queryParamValue?: string;
    };
    BaseResponseSurgerySection: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['SurgerySection'];
    };
    CompareCoverage: {
      /** Format: int32 */
      productCoverage?: number;
      /** Format: int32 */
      averageCoverage?: number;
    };
    SurgerySection: {
      displayName?: string;
      hyphenCase?: string;
      surgery?: components['schemas']['CompareCoverage'];
      surgeryType?: components['schemas']['SurgeryTypeSection'];
    };
    SurgeryTypeSection: {
      type1?: components['schemas']['CompareCoverage'];
      type2?: components['schemas']['CompareCoverage'];
      type3?: components['schemas']['CompareCoverage'];
      type4?: components['schemas']['CompareCoverage'];
      type5?: components['schemas']['CompareCoverage'];
    };
    BaseResponseMajorDiseaseSection: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['MajorDiseaseSection'];
    };
    MajorDiseaseSection: {
      displayName?: string;
      hyphenCase?: string;
      additionalInfo?: string;
      sections?: components['schemas']['MajorDiseaseSubSection'][];
    };
    MajorDiseaseSubSection: {
      displayName?: string;
      diagnosis?: components['schemas']['CompareCoverage'];
      injury?: components['schemas']['CompareCoverage'];
    };
    BaseResponseDailyHospitalizationSection: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['DailyHospitalizationSection'];
    };
    DailyHospitalizationSection: {
      displayName?: string;
      hyphenCase?: string;
      diseaseDailyHospitalization?: components['schemas']['CompareCoverage'];
    };
    BaseResponseDisabilitySection: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['DisabilitySection'];
    };
    DisabilitySection: {
      displayName?: string;
      hyphenCase?: string;
      coverage?: components['schemas']['CompareCoverage'];
    };
    BaseResponseDeathSection: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['DeathSection'];
    };
    DeathSection: {
      displayName?: string;
      hyphenCase?: string;
      coverage?: components['schemas']['CompareCoverage'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getPostDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostDetailResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  updatePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PostUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostCreateResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deletePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getAllPosts: {
    parameters: {
      query?: {
        sort?: 'LATEST' | 'POPULAR';
        category?: 'ALL' | 'QNA' | 'INFORMATION' | 'CONVERSATION';
        cursor?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseSliceResponsePostSummaryResponseLong'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PostCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostCreateResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createPostLike: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deletePostLike: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getComments: {
    parameters: {
      query?: {
        cursor?: number;
        size?: number;
      };
      header?: never;
      path: {
        'post-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseSliceResponseCommentWithImagesResponseLong'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostCreateResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCommentReply: {
    parameters: {
      query?: {
        cursor?: number;
        size?: number;
      };
      header?: never;
      path: {
        'post-id': number;
        'comment-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseSliceResponseCommentReplyWithImagesResponseLong'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createCommentReply: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
        'comment-id': number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentReplyCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseTokenReissueResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: {
        'redirect-url'?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseString'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  kakaoCallback_1: {
    parameters: {
      query: {
        code: string;
        'redirect-url'?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseKaKaoLoginResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  kakaoCallback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OAuthLoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseKaKaoLoginResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  issueReport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InsuranceReportRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseIssueInsuranceReportResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createdUrls: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PresignedUrlRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePresignedUrlResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateProfileRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
        'comment-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  updateComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
        'comment-id': number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostCreateResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deleteCommentReply: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
        'comment-id': number;
        'comment-reply-id': number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  updateCommentReply: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'post-id': number;
        'comment-id': number;
        'comment-reply-id': number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentReplyUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getMyLastInsuranceReportSummary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseInsuranceReportSummaryResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getMyPosts: {
    parameters: {
      query?: {
        cursorId?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseSliceResponseMyPostSummaryResponseLong'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getMyComments: {
    parameters: {
      query?: {
        cursorId?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseSliceResponseMyCommentSummaryResponseLong'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUserProfileResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getJobs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseJobResponses'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getInsurancesOptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseInsuranceOptionsResponse'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getDiagnosedDisease: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseDiagnosedDiseaseResponses'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCoverageSelect: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCoveragePreferenceResponses'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getTrendPosts: {
    parameters: {
      query?: {
        size?: number;
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseTrendingPostsResponses'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  searchPosts: {
    parameters: {
      query: {
        keyword: string;
        cursor?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseSliceResponsePostSummaryResponseLong'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getReport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        'insurance-report-id': string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseInsuranceReportResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getReportSurgerySection: {
    parameters: {
      query: {
        section: string;
      };
      header?: never;
      path: {
        'insurance-report-id': string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseSurgerySection'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getReportMajorSection: {
    parameters: {
      query: {
        section: string;
      };
      header?: never;
      path: {
        'insurance-report-id': string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseMajorDiseaseSection'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getHospitalizationSection: {
    parameters: {
      query: {
        section: string;
      };
      header?: never;
      path: {
        'insurance-report-id': string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseDailyHospitalizationSection'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getDisabilitySection: {
    parameters: {
      query: {
        section: string;
      };
      header?: never;
      path: {
        'insurance-report-id': string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseDisabilitySection'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getDeathSection: {
    parameters: {
      query: {
        section: string;
      };
      header?: never;
      path: {
        'insurance-report-id': string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseDeathSection'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  unlink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      /** @description 경로 변수 값이 누락되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 JWT입니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 지원하지 않는 URL입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 유효하지 않은 Http 메서드입니다. */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 외부 서버 오류입니다. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
