export const homeCardConfig = [
  { icon: '/3d_brain.webp', target: '뇌혈관질환' },
  { icon: '/3d_cancer.webp', target: '암' },
  { icon: '/3d_die.webp', target: '사망' },
  { icon: '/3d_disability.webp', target: '장해' },
  { icon: '/3d_heart.webp', target: '심장질환' },
  { icon: '/3d_hospital.webp', target: '입원' },
  { icon: '/3d_surgery.webp', target: '수술' },
  { icon: '/3d_brain.webp', target: '뇌혈관질환' },
  { icon: '/3d_cancer.webp', target: '암' },
  { icon: '/3d_die.webp', target: '사망' },
  { icon: '/3d_disability.webp', target: '장해' },
  { icon: '/3d_heart.webp', target: '심장질환' },
  { icon: '/3d_hospital.webp', target: '입원' },
  { icon: '/3d_surgery.webp', target: '수술' },
];
